# Generated by Django 5.2.5 on 2025-08-15 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en progress', 'En Progress'), ('solved', 'Solved')], default='nouvelle', max_length=20)),
                ('type', models.CharField(choices=[('déchets', 'Déchets'), ('éclairage défectueux', 'Eclairage Défectueux'), ('nids-de-poule', 'Nids-de-poule'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reclamations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
